import { AccountRow } from '@core/types/dashboard.types';
import { ColumnDef } from '@core/types/table.types';

export const ACCOUNTS_MOCK_DATA: AccountRow[] = [
  {
    account: { name: 'NAMEX Tech Solutions', type: 'Large Enterprise' },
    line: 'D&O Liability',
    broker: 'Willis Towers',
    renewalDate: '2025-04-16',
    premium: 2300000,
    ratedPremium: 2800000,
    lossRatio: 0.32,
    appetite: 'high',
    status: 'Active',
    triage: 180,
    winnability: 'Very Strong',
  },
  {
    account: { name: 'Alliance Healthcare Systems', type: 'Mid-Market' },
    line: 'Medical Malpractice',
    broker: 'Aon Risk',
    renewalDate: '2025-06-30',
    premium: 1700000,
    ratedPremium: 1900000,
    lossRatio: 0.38,
    appetite: 'medium',
    status: 'Under review',
    triage: 165,
    winnability: 'Strong',
  },
  {
    account: { name: 'Maritime Logistics Corp', type: 'Shipping/Logistics' },
    line: 'Marine Cargo',
    broker: 'Marsh McLennan',
    renewalDate: '2025-09-05',
    premium: 875000,
    ratedPremium: 920000,
    lossRatio: 0.25,
    appetite: 'high',
    status: 'Active',
    triage: 182,
    winnability: 'Very Strong',
  },
  {
    account: { name: 'GreenField Energy Ltd', type: 'Energy Sector' },
    line: 'Environmental Liability',
    broker: 'Aon Risk',
    renewalDate: '2025-07-22',
    premium: 1200000,
    ratedPremium: 1400000,
    lossRatio: 0.67,
    appetite: 'cautious',
    status: 'Under review',
    triage: 158,
    winnability: 'Medium',
  },
];

export const ACCOUNTS_COLUMNS_DATA: ColumnDef[] = [
  { key: 'account', header: 'ACCOUNT NAME/TYPE', width: 380 },
  { key: 'line', header: 'LINE', width: 160 },
  { key: 'broker', header: 'BROKER', width: 180 },
  { key: 'renewalDate', header: 'RENEWAL DATE', width: 80 },
  { key: 'premium', header: 'PREMIUM', width: 80 },
  { key: 'ratedPremium', header: 'RATED PREMIUM', width: 140, align: 'end' },
  { key: 'lossRatio', header: 'LOSS RATIO', width: 120 },
  { key: 'appetite', header: 'APPETITE', width: 130 },
  { key: 'status', header: 'STATUS', width: 140 },
  { key: 'triage', header: 'TRIAGE', width: 110, align: 'center' },
  { key: 'winnability', header: 'WINNABILITY', width: 200 },
];
